version: '3.7'

services:
  https-portal:
    image: steveltn/https-portal:${HTTPS_PORTAL_VERSION}
    environment:
      DOMAINS: >
        ${HTTPS_PORTAL_HOSTNAME} -> http://app:80,
      CLIENT_MAX_BODY_SIZE: 1024M
      SERVER_NAMES_HASH_BUCKET_SIZE: 1024
      STAGE: ${HTTPS_PORTAL_MODE}
    volumes:
      - https-portal_certs:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PIPELINE_PHP_VERSION}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 80
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mariadb_data:
  https-portal_certs:
